# Generated by Django 5.2.6 on 2025-09-14 09:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('training_wear', 'Training Wear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('collectibles', 'Collectibles'), ('fan_gear', 'Fan Gear')], default='jerseys', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('total_sold', models.IntegerField(default=0)),
            ],
        ),
    ]
