# Generated by Django 5.2.6 on 2025-09-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jerseys', 'Jerseys'), ('shorts', 'Shorts'), ('training_wear', 'Training Wear'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('equipment', 'Equipment'), ('collectibles', 'Collectibles'), ('fan_gear', 'Fan Gear')], default='jerseys', max_length=20),
        ),
    ]
